Adding workflow templates for Java
OpenGov/.github pull request #1
Opened 2022-05-17 09:04 UTC by sandeebh

This PR will add a starter workflow templates for java CI, which can be shared across the Org to get started with the workflows with github actions.

2022-05-17 14:45 UTC, jdellostritto commented on workflow-templates/build-gradle.properties.json
> +	"nodejs"
?? Why is nodejs here?

2022-05-17 14:48 UTC, jdellostritto commented on README.md
> +The starter workflows contains the CI workflows for Node and Java for doing below actions
We will need to make sure for the java project that we identify the necessary requirements for gradle and Jib. We should add the snippets here for that. Specifically from the gradle.build file.

2022-05-17 18:05 UTC, jspiro commented on README.md
> +This repository will have the starter workflows for using github actions.
```suggestion
This repository has the starter workflows for using GitHub Actions.
```

2022-05-17 18:07 UTC, jspiro commented on README.md
> +The starter workflows contains the CI workflows for Node and Java for doing below actions
Does `.github-private` support hosting these workflows? I'm not convinced they offer much open-source value. You can reach out to our account manager at GH to ask about their roadmap.

2022-05-17 18:09 UTC, jspiro commented on workflow-templates/PR-Build-Gradle-Lacework.yaml
> +        - name: Run Lacework
The whole reason we recreated the repo was to avoid disclosing our security tooling, which we have again done here, and in three other files. What changes were made since the previous repo to obfuscate this?

2022-05-17 18:12 UTC, jspiro submitted a review, later dismissed
I feel we should be looking much more closely at what we're making public long before doing so and having public discussions about internal issues.

If this is the only way to provide templates to OpenGov at this time, then let's have an EOL schedule for it when GH provides an alternate means via `.github-private` for example.

I'm also wondering why our security tooling is still being disclosed. Force-pushing won't clean it up, so I feel we should make this private, finish our discussions, and then remake the repo again cleanly.

2022-05-17 20:18 UTC, highb commented on workflow-templates/PR-Build-Gradle-Lacework.yaml
> +          git fetch --prune --unshallow
Why do we need to fetch the entire repository history? Sonar isn't going to analyze all of it, is it?

2022-05-17 20:21 UTC, highb commented on workflow-templates/PR-Build-Gradle-Lacework.yaml
> +            run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
This isn't necessary, `$GITHUB_REF_NAME` should get the ref that kicked off the event, regardless of if that was a PR or a push to `main`.

2022-05-17 20:56 UTC, highb requested changes

2022-05-17 20:56 UTC, highb commented on workflow-templates/PR-Build-Gradle-Lacework.yaml
> +  Integration-tests:
This should be made all lowercase in order to be consistent with the other actions.

2022-05-17 20:56 UTC, highb commented on workflow-templates/PR-Build-Gradle-Lacework.yaml
> +          name: Build and push Image
Capitalization: `Build and Push Image`

2022-05-17 20:56 UTC, highb commented on workflow-templates/PR-Build-Gradle-Lacework.yaml
> +      name: integration-tests
We should be consistent with the naming here: `Integration Tests`

2022-05-17 20:56 UTC, highb commented on workflow-templates/PR-Build-Gradle-Lacework.yaml
> +          uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
These git SHAs are going to be hard to keep track of. I would suggest that we either add the SemVer here i.e. `v1.0.4` and not use the sha so that Dependabot can detect when the workflow has become out of date.

2022-05-17 20:56 UTC, highb commented on workflow-templates/PR-Build-Gradle-Lacework.yaml
> +              TAG: PR-${{github.event.pull_request.number }}
Instead of manually specifying the `TAG` here, please use the official Docker `meta` action. [Refer to the workflow that I setup on `simple-java-api`.](https://github.com/OpenGov/simple-java-api/blob/main/.github/workflows/pr-build-gradle.yml#L102)

```
          - name: Docker meta
            id: meta
            uses: docker/metadata-action@v4
            with:
              images: ${{ env.image-name }}
              tags: |
                type=sha
                type=ref,event=branch
                type=ref,event=tag
                type=ref,event=pr
...
          - name: Split tags for Jib
            run: |
              SPLIT=$(echo "${{ steps.meta.outputs.tags }}" | xargs -n 1 | sed 's/.*:\(.*\)/\1/')
              echo "::set-output name=tags::$(echo ${SPLIT} | xargs echo | tr ' ' ',')"
              echo "::set-output name=tag-first::$(echo ${SPLIT} | cut -d' ' -f1)"
            id: split-tags

          - name: Build and Push with Gradle
            env:
              TAG: ${{ steps.generate-tag.outputs.tag }}
            uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
            with:
              arguments: jib -Djib.to.tags=${{ steps.split-tags.outputs.tags }}t -Djib.to.auth.username=${{ secrets.DOCKER_HUB_INTEGRATION_USER }} -Djib.to.auth.password=${{ secrets.DOCKER_HUB_INTEGRATION_ACCESS_TOKEN }}
```

2022-05-17 20:56 UTC, highb commented on workflow-templates/PR-Build-Gradle-Lacework.yaml
> +        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
```suggestion
        uses: gradle/wrapper-validation-action@v1.0.4
```

2022-05-17 20:56 UTC, highb commented on workflow-templates/PR-Build-Gradle-Lacework.yaml
> +        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
```suggestion
        uses: gradle/gradle-build-action@v2.1.6
```

2022-05-17 20:56 UTC, highb commented on workflow-templates/PR-Build-Gradle-Lacework.yaml
> +            uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
```suggestion
            uses: gradle/gradle-build-action@v2.1.6
```

2022-05-17 20:56 UTC, highb commented on workflow-templates/PR-Build-Gradle-Lacework.yaml
> +  Integration-tests:
```suggestion
  integration-tests:
```

2022-05-17 20:56 UTC, highb commented on workflow-templates/PR-Build-Gradle-Lacework.yaml
> +      name: integration-tests
```suggestion
      name: Integration Tests
```

2022-05-17 20:56 UTC, highb commented on workflow-templates/PR-Build-Gradle-Lacework.yaml
> +          uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
```suggestion
          uses: gradle/wrapper-validation-action@v1.0.4
```

2022-05-17 20:56 UTC, highb commented on workflow-templates/PR-Build-Gradle-Lacework.yaml
> +          uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
```suggestion
          uses: gradle/gradle-build-action@v2.1.6
```

2022-05-17 20:56 UTC, highb commented on workflow-templates/PR-build-gradle.properties.json
> +        "node"
```suggestion
        "java"
```

2022-05-17 20:56 UTC, highb commented on workflow-templates/PR-Build-Gradle-Lacework.properties.json
> +        "node"
```suggestion
        "java"
```

2022-05-17 20:56 UTC, highb commented on workflow-templates/PR-Build-Gradle-Lacework.yaml
> +
This is unnecessary if we are pushing images to DockerHub. If we were using GHP for our images, this action doesn't handle image cleanup -- [as discussed in this issue](https://github.com/actions/delete-package-versions/issues/35). The suggested solution in that issue is to use https://github.com/snok/container-retention-policy but we don't need to worry about that for now while. we are still using DockerHub.
```suggestion
```

2022-05-17 20:56 UTC, highb commented on workflow-templates/PR-Build-Gradle-Lacework.yaml
> +            docker pull ${{ secrets.DOCKER_HUB_ORG }}/${{ github.event.repository.name }}:PR-${{github.event.pull_request.number }}
This will need to use the Docker `meta` generated tags, as mentioned in the above comment, [please refer to the workflow that I setup on simple-java-api.](https://github.com/OpenGov/simple-java-api/blob/main/.github/workflows/pr-build-gradle.yml#L102)

2022-05-17 20:56 UTC, highb commented on workflow-templates/PR-build-gradle.properties.json
> +        "node"
```suggestion
        "java"
```

2022-05-17 20:56 UTC, highb commented on workflow-templates/PR-build-gradle.yaml
> +        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
```suggestion
        uses: gradle/wrapper-validation-action@v1.0.4
```

2022-05-17 20:56 UTC, highb commented on workflow-templates/PR-build-gradle.yaml
> +        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
```suggestion
        uses: gradle/gradle-build-action@v2.1.6
```

2022-05-17 20:56 UTC, highb commented on workflow-templates/PR-build-gradle.yaml
> +          name: Build and push Image
```suggestion
          name: Build and Push Image
```

2022-05-17 20:56 UTC, highb commented on workflow-templates/PR-build-gradle.yaml
> +            uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
```suggestion
            uses: gradle/gradle-build-action@v2.1.6
```

2022-05-17 20:56 UTC, highb commented on workflow-templates/PR-build-gradle.yaml
> +
Same comment and reasoning as above.

```suggestion
```

2022-05-17 20:56 UTC, highb commented on workflow-templates/PR-build-gradle.yaml
> +name: PR-CI
Why do we have both this workflow and `workflow-templates/PR-Build-Gradle-Lacework.yaml`? They perform the same set of actions. We should consolidate on one or the other in order to reduce confusion when developers adopt these.

Additionally, there is no need to have a completely separate workflow for PRs and pushing to main. We can set conditional logic on the workflow steps that will modify the behavior appropriately depending on the context the workflow is being started by. For an example [please refer to the workflow that I setup on simple-java-api.](https://github.com/OpenGov/simple-java-api/blob/main/.github/workflows/pr-build-gradle.yml#L102)

I would recommend that we consolidate `workflow-templates/PR-Build-Gradle-Lacework.yaml` and `workflow-templates/PR-build-gradle.yaml` into a single `workflow-templates/gradle-jib.yaml` workflow for simplicity sake.

2022-05-17 20:56 UTC, highb commented on workflow-templates/PR-build-gradle.yaml
> +          uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
```suggestion
          uses: gradle/wrapper-validation-action@v1.0.4
```

2022-05-17 20:56 UTC, highb commented on workflow-templates/PR-build-gradle.yaml
> +          uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
```suggestion
          uses: gradle/gradle-build-action@v2.1.6
```

2022-05-17 20:56 UTC, highb commented on workflow-templates/build-gradle.properties.json
> +	"nodejs"
```suggestion
        "java"
```

2022-05-17 20:56 UTC, highb commented on workflow-templates/build-gradle.yaml
> +name: build gradle code
```suggestion
name: Build Gradle Project
```

2022-05-17 20:56 UTC, highb commented on workflow-templates/build-gradle.yaml
> +        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
```suggestion
        uses: gradle/wrapper-validation-action@v1.0.4
```

2022-05-17 20:56 UTC, highb commented on workflow-templates/build-gradle.yaml
> +        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
```suggestion
        uses: gradle/gradle-build-action@v2.1.6
```

2022-05-17 20:56 UTC, highb commented on workflow-templates/build-gradle.yaml
> +        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
```suggestion
        uses: gradle/gradle-build-action@v2.1.6
```

2022-05-17 20:56 UTC, highb commented on workflow-templates/code-coverage.properties.json
> +    "name": "Sonar scan Workflow",
```suggestion
    "name": "Sonar Scan: Gradle",
```

2022-05-17 20:56 UTC, highb commented on workflow-templates/code-coverage.properties.json
> +	"nodejs"
```suggestion
        "java"
```
This is still a Java-only workflow, as it requires Gradle.

2022-05-17 20:56 UTC, highb commented on workflow-templates/code-coverage.yaml
> +name: static code analysis
```suggestion
name: Sonar Scan: JDK
```

2022-05-17 20:56 UTC, highb commented on README.md
> +The starter workflows contains the CI workflows for Node and Java for doing below actions
I don't believe workflow templates are intended to include the actual project setup files. They are intended to be used with an existing project that needs to have GHA workflows added to it.

If we want to provide the complete project for developers to adopt, we need to setup the EngOps sample repos to be usable as templates and provide some method of creating them via Terraform, or at least some directions on how to force push the template repo over a new repo's code for initial setup.

2022-05-17 20:56 UTC, highb commented on README.md
> +2. Image Build and push to registry (Dockerhub)
```suggestion
2. Image Build and Push to Registry (DockerHub)
```

2022-05-17 20:56 UTC, highb commented on README.md
> +To use the starter workflows, for the organization , follow below steps :
```suggestion
To use the starter workflows, follow the below steps :
```

2022-05-17 20:56 UTC, highb commented on README.md
> +1. Go to actions and click on new workflow
```suggestion
1. Go to "Actions" and click on "New Workflow"
```

2022-05-17 20:56 UTC, highb commented on README.md
> +3. choose appropriate starter workflow from the list
```suggestion
3. Choose the appropriate starter workflow from the list
```

2022-05-17 20:56 UTC, highb commented on README.md
> +4. commit and your workflow will be created.
```suggestion
4. Commit and your workflow will be created.
```

2022-05-17 20:56 UTC, highb commented on README.md
> +To run the workflows from this repository, organisation or repo should have below secrets defined.
```suggestion
To run the workflows from this repository, organization or repo should have below secrets defined.
```

2022-05-17 20:56 UTC, highb commented on README.md
> +DOCKER_HUB_ACCESS_TOKEN - Docker api token for login
```suggestion
DOCKER_HUB_ACCESS_TOKEN - Docker API token for login
```

2022-05-17 20:56 UTC, highb commented on README.md
> +DOCKER_HUB_ORG - name of organisation in Dockerhub
```suggestion
DOCKER_HUB_ORG - Name of organization in DockerHub
```

2022-05-18 05:11 UTC, sandeebh commented on workflow-templates/PR-Build-Gradle-Lacework.yaml
> +        - name: Run Lacework
The action that we are using is anyways going to disclose that we are using Lacework. 
"uses: lacework/lw-scanner-action@v0.7.1"

2022-05-18 05:13 UTC, sandeebh commented on workflow-templates/PR-Build-Gradle-Lacework.yaml
> +
yeah missed this .. thanks @highb

2022-05-18 05:17 UTC, sandeebh commented on workflow-templates/PR-Build-Gradle-Lacework.yaml
> +              TAG: PR-${{github.event.pull_request.number }}
Having a look at this

2022-05-18 05:23 UTC, sandeebh commented on workflow-templates/build-gradle.properties.json
> +	"nodejs"
Fixed

2022-05-18 05:25 UTC, sandeebh commented on README.md
> +The starter workflows contains the CI workflows for Node and Java for doing below actions
@jspiro this is the repo for only having starter workflows. Engops service templates repositories will be having the project structure and workflows together. I will check on .github -private, thanks.

2022-05-18 06:01 UTC, sandeebh commented on workflow-templates/PR-Build-Gradle-Lacework.yaml
> +          git fetch --prune --unshallow
I was getting the warning similar to this https://stackoverflow.com/questions/59000099/sonarqube-with-shallow-clone-warning-even-with-shallow-disabled-on-jenkins-build and so added unshallow.

2022-05-18 12:30 UTC, sandeebh commented on workflow-templates/PR-Build-Gradle-Lacework.yaml
> +              TAG: PR-${{github.event.pull_request.number }}
@highb changed this

2022-05-18 17:23 UTC, highb commented on workflow-templates/PR-Build-Gradle-Lacework.yaml
> +          git fetch --prune --unshallow
Interesting, that seems like an expensive operation for SonarQube to require but if that's how it has to be configured, so be it. 👍

2022-05-18 17:42 UTC, highb requested changes
Just a few more refinements

2022-05-18 17:42 UTC, highb commented on workflow-templates/PR-Build-Gradle-Lacework.yaml
> +      - name: 'Checkout repository on branch: ${{ github.REF }}'
```suggestion
      - name: 'Checkout repository on branch: ${{ github.HEAD_REF }}'
```

2022-05-18 17:42 UTC, highb commented on workflow-templates/code-coverage.yaml
> +      - name: 'Checkout repository on branch: ${{ github.REF }}'
```suggestion
      - name: 'Checkout repository on branch: ${{ github.HEAD_REF }}'
```

2022-05-18 17:42 UTC, highb commented on workflow-templates/PR-Build-Gradle-Lacework.yaml
> +              TAG: PR-${{github.event.pull_request.number }}
Looks good, thank you!

2022-05-18 17:42 UTC, highb commented on workflow-templates/PR-Build-Gradle-Lacework.yaml
> +        - name: Run Lacework
I don't believe CP has the bandwidth to create wrapper actions as you are requesting but GST is welcome to create and maintain whatever actions you deem necessary for helping to drive adoption and good standards with these tools.

I think for this initial establishing of patterns, it is going to be more light-weight, understandable, and agile for teams if we use the upstream action directly. We can iterate on it further over time and determine if a re-usable wrapper action is necessary.

2022-05-18 17:42 UTC, highb commented on workflow-templates/PR-Build-Gradle-Lacework.yaml
> +            FAIL_BUILD: false
@jspiro What is GST's stance on the security scan here? I would think that we should fail the build if there is a fixable security issue detected.

2022-05-18 18:25 UTC, jspiro commented on workflow-templates/PR-Build-Gradle-Lacework.yaml
> +            FAIL_BUILD: false
We agree, so long as the false-positive rate is low to zero. Can we scope this to a variable or certain repos initially and see how it goes, or are you already reasonably confident in this?

2022-05-18 18:26 UTC, jspiro commented on workflow-templates/PR-Build-Gradle-Lacework.yaml
> +        - name: Run Lacework
I'm only suggesting options. If .github-private can be used, this is irrelevant. If .github can stay private for now, this is irrelevant.

2022-05-18 23:47 UTC, highb commented on workflow-templates/PR-Build-Gradle-Lacework.yaml
> +              TAG: PR-${{github.event.pull_request.number }}
```suggestion
```

This `env` is no longer necessary.

2022-05-19 00:33 UTC, highb commented on workflow-templates/PR-Build-Gradle-Lacework.yaml
> +            FAIL_BUILD: false
I'm not confident in it at all, I've never had a Lacework scan actually work so far. If you're not confident that it will not result in any false-positives then sure let's keep `FAIL_BUILD: false` here.

2022-05-19 16:32 UTC, jdellostritto commented on README.md
> +The starter workflows contains the CI workflows for Node and Java for doing below actions
Keep it private for now. We can not block this effort... we can revisit alternative and viability for making this public later.

2022-05-19 16:33 UTC, jdellostritto approved these changes

2022-05-19 17:11 UTC, highb approved these changes
Thank you for your patience with all of our PR reviews @sandeebh . This looks good for now, +1 on keeping this private for now.

2022-05-19 18:18 UTC, jspiro commented on workflow-templates/PR-Build-Gradle-Lacework.yaml
> +            FAIL_BUILD: false
New services should not be able to opt out. Maybe we can have a bypass list of repos that start with it off.

OTOH what is the behavior of it failing? If we don't require the check/step, it should still fail so we know it failed. If leaving this off means that's obscured, then I would make it true.

2022-05-20 06:17 UTC, merged

2022-05-20 06:18 UTC, sandeebh commented
> Thank you for your patience with all of our PR reviews @sandeebh . This looks good for now, +1 on keeping this private.

Yeah.. thanks okay for now. I checked and the workflows are available even the repo is Private. Thank you.